### ISSUE TITLE
hdf5 issue

### ISSUE THREAD

**Issue by rvinaybharadwaj** [ECP-Astro/thornado_mini#1]
I am trying to build thornado_mini with hdf5 1.10.3 and openblas 0.3.3, but keep getting build errors in the lines of undefined reference to symbol:
wlIOModuleHDF.o: In function `__wliomodulehdf_MOD_read1dhdf_string':
wlIOModuleHDF.f90:(.text+0x4b): undefined reference to `__h5global_MOD_h5t_native_character'
....

 Is there a specific version of hdf5 and LAPACK that is recommended?

**Comment by bronson79** [comment]
It may be that you don't have Fortran bindings built for your HDF5 installation, or don't have the resulting Fortran modules in the link path? 1.10.x and 1.8.x versions have both worked in the past.
